---
- name: Install JDK and JRE on Windows VM
  hosts: all
  tasks:
    - name: Download JDK installer
      win_get_url:
        url: "{{ jdk_url }}"
        dest: "C:\\temp\\jdk-installer.exe"

    - name: Install JDK silently
      win_package:
        path: "C:\\temp\\jdk-installer.exe"
        arguments:
          - /s
          - INSTALLDIR=C:\\Program Files\\Java\\jdk1.8.0_431
        state: present

    - name: Verify Java version
      win_command: '"C:\\Program Files\\Java\\jdk1.8.0_431\\bin\\java.exe" -version'
      register: java_version

    - name: Display Java version
      debug:
        msg: "{{ java_version.stderr }}"
